export const home = (req, res) => res.send("Home");
export const join = (req, res) => res.send("Join");
export const login = (req, res) => res.send("Login");
export const confirmAccount = (req, res) => res.send("Confirm-account");
export const courses = (req, res) => res.send("Courses");
export const coursesNew = (req, res) => res.send("Courses New");
export const coursesMine = (req, res) => res.send("Courses Mine");
export const apiDocument = (req, res) => res.send("Api document");
export const buy = (req, res) => res.send("buy");
export const refund = (req, res) => res.send("refund");
export const remove = (req, res) => res.send("remove");
export const edit = (req, res) => res.send("edit");